// Generated by Wrangler on Thu Jun 20 2024 00:21:20 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	GITHUB_CLIENT_ID: "Ov23liBj2OQaGDXFtu4D";
	GITHUB_CLIENT_SECRET: "07233e7ed1d5a05daff55005a6c422a5ae1f314c";
	GOOGLE_CLIENT_ID: "633602123635-sf22dri707rvhgc486r2cokn81c7edp3.apps.googleusercontent.com";
	GOOGLE_CLIENT_SECRET: "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";
	GOOGLE_REDIRECT_URI: "http://localhost:5173/googleredirect";
	R2: R2Bucket;
	DB: D1Database;
}
