# Cloudflare pages requires a top level name attribute
name = "gallery"

# Cloudflare Pages will ignore wrangler.toml without this line
pages_build_output_dir = "./build/client"

# Fixes "no such module 'node:events'"
compatibility_flags = [ "nodejs_compat" ]

# Fixes "compatibility_flags cannot be specified without a compatibility_date"
compatibility_date = "2024-04-18"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "db"
database_id = "16785b38-d796-4dde-b7a5-5d0392fc3881"
migrations_dir="./app/drizzle/migrations"


[[r2_buckets]]
binding = "R2"
bucket_name = "artworks"

[vars]
GITHUB_CLIENT_ID="Ov23liBj2OQaGDXFtu4D"
GITHUB_CLIENT_SECRET="07233e7ed1d5a05daff55005a6c422a5ae1f314c"
GOOGLE_CLIENT_ID="633602123635-sf22dri707rvhgc486r2cokn81c7edp3.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"
GOOGLE_REDIRECT_URI="josiahzella.pages.dev/googleredirect"